export default [
  "dig deep to understand complex problems and create simple solutions",
  "do visual design with accessible contrast ratios",
  "use newfangled CSS whenever possible",
  "create NPM packages to share design system components and tokens",
  "collaborate well with designers, developers, and other stakeholders",
  "sketch wireframes and diagrams in pen",
  "have opinions about fonts",
  "try a lot of UX design and prototyping tools",
  "do CI/CD for design systems in Github",
  "create lots of Figma libraries",
  "take notes in Markdown",
  "come up with weird workarounds for missing Figma features",
  "use regular expressions in VS Code to find and replace",
  "update Figma libraries when they release cool new features",
  "make dad jokes during meetings sometimes",
  "use custom mouse bindings to go up and down Figma’s layer tree",
  "like green",
  "…just go look at the case studies, why don't you"
];